### ISSUE TITLE
Integrated with Victor Hugo and Netlify

### ISSUE THREAD

**Issue by eliwilliamson** [adrinux/web-starter-hugo#45]
This is a great pipeline - i'd love to see it even more useable by leveraging continuous deployment with [Netlify](www.netlify.com) and [Victor Hugo](https://github.com/netlify/victor-hugo).

**Comment by adrinux** [comment]
Unfortunately somewhat neglected, hoping to do a revamp and make some big changes this autumn.

**Comment by adrinux** [comment]
Opening this again to remind me to look into these for version 2.

**Comment by adrinux** [comment]
Victor Hugo is in effect an alternative to web-starter-hugo (wsh) with good Netlify integration. IF you're using Netlify it makes sense to use Victor Hugo. I don't see the point of duplicating that functionality in wsh. Closing this.
